### ISSUE TITLE
Implement Playwright Visual Regression Testing

### ISSUE THREAD

**Issue by jerseycheese** [jerseycheese/Narraitor#384]
## Plain Language Summary
Add visual regression testing to our CI pipeline to automatically catch visual UI changes and regressions.

## Current Feature
Our CI currently runs E2E tests with Playwright but doesn't include visual comparison testing.

## Domain
- [x] Other: DevOps/CI

## Enhancement Description
Implement visual regression testing using Playwright's built-in screenshot comparison capabilities. This will allow us to automatically detect unintended visual changes in our UI components and pages.

Key tasks:
1. Update Playwright configuration to support visual comparisons
2. Create initial visual tests for key pages/components
3. Generate baseline screenshots
4. Configure CI workflow to run visual tests
5. Add artifact upload for failed visual tests

## Reason for Enhancement
Visual regressions are easy to miss with traditional testing approaches. Adding visual regression testing will:
- Catch unintended visual changes early
- Provide a history of UI evolution
- Reduce manual testing burden

## Possible Implementation
```typescript
// Configure Playwright for screenshot testing
import { defineConfig } from '@playwright/test';

export default defineConfig({
  // Existing config
  expect: {
    toHaveScreenshot: {
      maxDiffPixels: 100,
      threshold: 0.2,
    }
  },
});

// Example test
test('component visual test', async ({ page }) => {
  await page.goto('/component-page');
  await expect(page).toHaveScreenshot('component.png');
});
```

Update GitHub workflow:
```yaml
# Add to CI workflow
- name: Run visual tests
  run: npx playwright test tests/visual/
- name: Upload visual test results on failure
  if: failure()
  uses: actions/upload-artifact@v3
  with:
    name: visual-test-results
    path: test-results/
```

## Alternatives Considered
- Chromatic: Commercial service, avoided due to preference for free/open-source
- Loki: Good but requires more setup than Playwright's built-in capabilities
- Percy: Commercial service with similar constraints to Chromatic

## Additional Context
We should establish a process for reviewing and approving intentional visual changes, possibly using a GitHub label like "visual-update" to trigger baseline updates.

Part of Epic #383
