### ISSUE TITLE
Add Cache Optimizations to CI Pipeline

### ISSUE THREAD

**Issue by jerseycheese** [jerseycheese/Narraitor#385]
## Plain Language Summary
Optimize our CI pipeline by implementing advanced caching strategies to speed up build and test runs.

## Current Feature
Current CI pipeline uses basic Node.js module caching but doesn't optimize for Next.js builds or Playwright browsers.

## Domain
- [x] Other: DevOps/CI

## Enhancement Description
Implement comprehensive caching strategies in our GitHub Actions workflow to significantly reduce CI execution time:

1. Cache Next.js build output
2. Cache Playwright browsers
3. Optimize dependency caching with better cache keys
4. Implement caching for Storybook builds

## Reason for Enhancement
Current CI runs are slower than necessary because they don't leverage caching effectively. This enhancement will:
- Reduce CI execution time by 40-60%
- Lower GitHub Actions billing usage
- Provide faster feedback to developers
- Reduce resource usage

## Possible Implementation
Add these cache configurations to the GitHub Actions workflow:

```yaml
# Next.js build cache
- name: Cache Next.js build
  uses: actions/cache@v3
  with:
    path: |
      .next/cache
    key: ${{ runner.os }}-nextjs-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
    restore-keys: |
      ${{ runner.os }}-nextjs-

# Playwright browsers cache
- name: Cache Playwright browsers
  uses: actions/cache@v3
  with:
    path: ~/.cache/ms-playwright
    key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

# Storybook cache
- name: Cache Storybook build
  uses: actions/cache@v3
  with:
    path: |
      node_modules/.cache/storybook
    key: ${{ runner.os }}-storybook-${{ hashFiles('**/*.stories.tsx', '**/*.stories.ts', '.storybook/**/*') }}
```

## Alternatives Considered
- Custom Docker images with pre-installed dependencies
- Self-hosted runners (more complex setup)
- Moving to a different CI provider (unnecessary given GitHub Actions capabilities)

## Additional Context
We should monitor the cache hit rates and adjust the cache keys if necessary to optimize performance further.

Part of Epic #383
