### ISSUE TITLE
Implement TypeScript Type Checking in CI

### ISSUE THREAD

**Issue by jerseycheese** [jerseycheese/Narraitor#386]
## Plain Language Summary
Add a dedicated step in our CI pipeline to perform strict TypeScript type checking to catch type errors early.

## Current Feature
Our CI runs linting and tests, but doesn't have a dedicated step for TypeScript type checking.

## Domain
- [x] Other: DevOps/CI

## Enhancement Description
Add a dedicated job in our CI workflow that runs TypeScript's compiler in type-checking mode without emitting code. This will:

1. Run TypeScript's compiler in strict checking mode
2. Provide clear error messages for type issues
3. Enforce type safety across the codebase

## Reason for Enhancement
Type errors can sometimes slip through linting and testing, especially with partial type checking. A dedicated type checking step will:
- Catch type errors earlier in the development process
- Prevent runtime errors in production
- Improve code quality and maintainability

## Possible Implementation
Add a new job to the GitHub Actions workflow:

```yaml
type-check:
  name: TypeScript Type Check
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run TypeScript type check
      run: npx tsc --noEmit
```

## Alternatives Considered
- Using ESLint with TypeScript plugins only (less comprehensive)
- Running type checking as part of the test job (less isolation)
- Using third-party type checking tools (unnecessary complexity)

## Additional Context
This should be a required check before merging to ensure type safety throughout the codebase.

Part of Epic #383
