### ISSUE TITLE
Add Security Scanning to CI Pipeline

### ISSUE THREAD

**Issue by jerseycheese** [jerseycheese/Narraitor#387]
## Plain Language Summary
Add automated security scanning to our CI pipeline to detect vulnerabilities in dependencies and code.

## Current Feature
Our CI pipeline currently doesn't include any security scanning capabilities.

## Domain
- [x] Other: DevOps/CI

## Enhancement Description
Implement security scanning in our CI pipeline with:

1. npm audit for dependency vulnerability scanning
2. CodeQL for static code analysis (optional)
3. Dependency version monitoring
4. Security report generation as build artifacts

## Reason for Enhancement
Security scanning is essential to identify:
- Vulnerable dependencies
- Potential security issues in code
- Outdated packages with known issues
- Compliance risks

## Possible Implementation
Add a new security job to the GitHub Actions workflow:

```yaml
security:
  name: Security Scan
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run npm audit
      run: npm audit --production --audit-level=high
    - name: Generate security report
      run: npm audit --json > security-report.json
    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.json
```

For CodeQL integration (optional):
```yaml
# Add after the checkout step
- name: Initialize CodeQL
  uses: github/codeql-action/init@v2
  with:
    languages: javascript
- name: Perform CodeQL Analysis
  uses: github/codeql-action/analyze@v2
```

## Alternatives Considered
- Commercial security scanning services (unnecessary cost for our current needs)
- Manual security reviews (not scalable)
- Third-party scanning tools (additional complexity)

## Additional Context
Consider making security scans non-blocking initially and gradually increasing strictness as we address identified issues.

Part of Epic #383
