### ISSUE TITLE
Optimize and Parallelize CI Workflow

### ISSUE THREAD

**Issue by jerseycheese** [jerseycheese/Narraitor#388]
## Plain Language Summary
Restructure our CI workflow to run jobs in parallel where possible and optimize overall execution time.

## Current Feature
Current CI pipeline runs most jobs sequentially and doesn't optimize job dependencies.

## Domain
- [x] Other: DevOps/CI

## Enhancement Description
Restructure our GitHub Actions workflow to:

1. Run independent jobs in parallel (lint, type-check, unit tests)
2. Optimize job dependencies to minimize critical path length
3. Split large test suites into parallel runs
4. Add workflow summary for execution time metrics
5. Implement test result collection and reporting

## Reason for Enhancement
The current sequential workflow is inefficient. Parallelizing and optimizing will:
- Reduce overall CI time significantly (30-50%)
- Provide faster feedback on errors
- Improve developer experience
- Scale better as the test suite grows

## Possible Implementation
Restructure GitHub workflow with optimized dependencies:

```yaml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Fast, parallel jobs that don't depend on each other
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    # No dependencies - can run immediately
    
  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    # No dependencies - can run immediately
    
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    # No dependencies - can run immediately
    
  # Jobs that depend on previous steps
  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint, type-check, unit-tests]
    
  storybook:
    name: Storybook Build
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    
  visual-tests:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    needs: [build, storybook]
    
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
```

## Alternatives Considered
- Self-hosted runners (adds complexity)
- Moving to a different CI provider (unnecessary)
- Custom Docker images with pre-built dependencies (more maintenance)

## Additional Context
We should monitor workflow execution times before and after this change to measure the improvement in CI performance.

Part of Epic #383
